# Generated by Django 5.0.2 on 2024-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_of_measure', models.CharField(choices=[('ltr', 'Liter'), ('kg', 'Kilogram'), ('pcs', 'Pieces')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
